language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer install

script:
  - phpunit

addons:
  code_climate:
    repo_token: d0a51df23c866e57ee5ad194357ce6726e0701f1622f25397931b81b19bc2246

after_script:
  - vendor/bin/test-reporter