<?php

namespace Galmi\XacmlBundle\Repository;

/**
 * PolicySetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolicySetRepository extends \Doctrine\ORM\EntityRepository
{
}
