<?php

namespace Galmi\XacmlBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Galmi\XacmlBundle\Entity\Policy;

/**
 * PolicyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolicyRepository extends EntityRepository
{
    /**
     * Find all top level policies for PDP
     *
     * @return Policy[]
     */
    public function findNotLinkedPolicies()
    {
        return $this->findBy(
            [
                'linked' => false,
                'active' => true,
            ]
        );
    }
}
